name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0' # Specify your Ruby version here
          bundler-cache: true # This will cache gems and run bundle install automatically

      - name: Build and deploy
        run: |
          JEKYLL_ENV=production bundle exec jekyll build
          mkdir -p ./_site
          cp -r ./_site/* ./_site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site